package-lock.json, package.json, src/lib/firebase/ReadFromCloudFirestore.ts, src/lib/firebase/WriteToCloudFirestore.ts, src/lib/firebase/useFirebase.ts, src/pages/auth/index.tsx, src/pages/index.tsx, src/pages/table/index.tsx, src/types/Table.ts, src/types/User.ts, tsconfig.json
Added basic support for firebase including initialization and read and write operations to cloud firestore. Also added auth and tables page routes
=> Firebase init

src/components/table/TableCard.tsx, src/layouts/table/MainTableLayout.tsx, src/lib/firebase/FirestoreOperations.ts, src/lib/firebase/table/TableOperations.ts, src/pages/table/index.tsx, src/types/Table.ts, src/types/User.ts
Created table interface and class
Created converter to make firebase reads and writes Table objects
Added templates for table layout and components
=> Created rw functions for table, more templating

src/components/table/tableSelection/createTable/CodeModal.tsx, src/components/table/tableSelection/createTable/CreateTable.tsx
- Created modal to display link or code upon creation of table
- Added copy buttons to automatically copy the code or link
=> Copy link or code modal

src/layouts/auth/ResetPassLayout.tsx
Error notification added. Handles Success and Error notification appropriately, and some UI changes.
=> Notification Updates and Link Changes

src/layouts/auth/LoginLayout.tsx
=> Update UI to LoginLayout

src/layouts/auth/InputResetPassLayout.tsx, src/layouts/auth/ResetPassLayout.tsx, src/pages/auth/inputresetpass.tsx
Trivial solution to not rendering the page before checking if the user has arrived from an email link
=> UI Changes to InputResetPassword Page

src/components/auth/ProtectedRoute.tsx, src/layouts/auth/ChangePasswordLayout.tsx, src/pages/auth/changePass.tsx, src/pages/tables/index.tsx
set state as null was not working - for Adhitya
=> protected route fix

src/layouts/auth/ChangePasswordLayout.tsx, src/lib/firebase/auth/AuthProvider.tsx, src/pages/auth/changePass.tsx
- Password changes working
- Needs a button and Header (NavBar)
=> Change Password Working

src/components/table/restaurantCards/CardStack.tsx, src/lib/utils/yelpAPI.tsx, src/pages/voting/index.tsx
Made buttons bigger, changed API limit parameter from 50 to 10, centered card stack on voting page
=> Resized buttons, changed API limit, fixed formatting on vote page

src/components/table/tableSelected/RestaurantPreview.tsx, src/components/table/tableSelected/TablePrefSidebar.tsx, src/components/table/tableSelected/TableUserSidebar.tsx, src/components/table/tableSelection/createTable/CreateTable.tsx, src/components/table/tableSelection/joinTable/JoinTable.tsx, src/layouts/table/tableSelected/RestaurantListLayout.tsx, src/layouts/table/tableSelected/TableSelectedLayout.tsx, src/layouts/table/tableSelection/UserTablesLayout.tsx, src/lib/firebase/table/TableOperations.ts, src/pages/tables/[tableid].tsx, src/pages/tables/index.tsx, src/types/Table.ts
-Added snapshot listeners for table data
-Updated create page to allow users to add zip, cuisine, and price
=> Create table updates

src/components/NavBar.tsx, src/layouts/table/tableSelection/TableSelectionLayout.tsx
Update to NavBar.
Installation and library error fixes.
=> (1 hr) Error and Installation errors

src/components/table/tableSelection/TableCard.tsx, src/layouts/table/tableSelection/TableSelectionLayout.tsx, src/pages/tables/[tableid].tsx
-Added functionality for user to leave table
-Added modal which confirms intent to leave
=> Leave table

src/layouts/table/tableSelection/TableSelectionLayout.tsx, src/pages/tables/[tableid].tsx
-Added notification when for when joining table
=> join table complete

src/components/NavBar.tsx, src/components/table/PriceSlider.tsx, src/components/table/SearchBar.tsx, src/components/table/tableSelected/TablePrefSidebar.tsx, src/layouts/table/tableSelected/TableSelectedLayout.tsx
UI updates:
- to NavBar
- to Price Slider
- to Price Slider
=> User preferences

src/components/NavBar.tsx, src/components/table/PriceSlider.tsx, src/components/table/SearchBar.tsx, src/components/table/tableSelected/TablePrefSidebar.tsx, src/layouts/table/tableSelected/TableSelectedLayout.tsx
UI for price preferences working. Still needs backend functionality.
=> Pricepreference

src/components/table/tableSelected/TableUserSidebar.tsx, src/layouts/auth/CreateAccountLayout.tsx, src/layouts/auth/CreateUsernameLayout.tsx, src/lib/firebase/auth/AuthOperations.tsx, src/types/User.ts
-Refactored and rewrote Dhruv's code
@Ddhawan2003 PLEASE MERGE THIS WITH YOUR BRANCH AND USE THE FUNCTIONS I MADE IN AUTHOPERATIONS FOR YOU!!!
=> Updated auth funcs and refactored firestore ops

src/components/table/tableSelected/CardUser.tsx, src/components/table/tableSelected/TableUserSidebar.tsx, src/components/table/tableSelection/TableCard.tsx, src/components/table/tableSelection/createTable/CreateTable.tsx, src/layouts/table/tableSelection/UserTablesLayout.tsx, src/pages/tables/[tableid].tsx, src/types/Table.ts
Users is now a dictionary in order to associate votes with users
=> Updates to tables firestore collections structure

src/components/NavBar.tsx, src/layouts/auth/DeleteAccountLayout.tsx, src/pages/auth/deleteAccount.tsx
- DeleteAccount functionality has been restored
=> DeleteAccount Restored

src/components/table/SearchBar.tsx, src/layouts/table/tableSelected/TableSelectedLayout.tsx
=> load more and cuisine filter fixed

src/components/NavBar.tsx, src/components/table/SearchBar.tsx, src/components/table/tableSelected/RestaurantPreviewCard.tsx, src/components/table/tableSelected/TablePrefSidebar.tsx, src/components/table/tableSelection/createTable/CreateTable.tsx, src/components/table/tableSelection/createTable/IndividualTable.tsx, src/layouts/table/tableSelected/TableSelectedLayout.tsx, src/lib/utils/yelpAPI.tsx, src/pages/tables/[tableid]/index.tsx, src/pages/tables/[tableid]/voting.tsx, src/types/Table.ts
=> back to home button, more data better cus search

src/components/NavBar.tsx, src/components/table/SearchBar.tsx, src/pages/tables/individual-table.tsx
- Search bar fix
- indiv table finished
- NavBar done
=> NavBar updates and SearchBar Fix

src/layouts/table/tableSelected/TableSelectedLayout.tsx
- Should be working
- essentially a vote button that takes the users to the voting page
=> Vote Button

src/pages/tables/[tableid]/results.tsx, src/pages/tables/[tableid]/voting.tsx
Waiting page dynamically displays number of users who are done voting, results page displays top 3 restaurants
=> Added results and waiting page

src/components/table/tableSelected/RestaurantPreviewCard.tsx, src/layouts/table/tableSelected/TableSelectedLayout.tsx
=> Sort by price

src/components/loaders/LoadingMainLogo.tsx, src/layouts/LoadingLayout.tsx, src/layouts/auth/CreateAccountLayout.tsx, src/layouts/auth/EmailVerificationLayout.tsx, src/layouts/auth/EmailVerifiedLayout.tsx, src/layouts/auth/LoginLayout.tsx, src/pages/auth/verification.tsx, src/pages/auth/verified.tsx, src/pages/tables/index.tsx, src/providers/AuthProvider.tsx
=> Email verification

src/layouts/auth/EmailVerifiedLayout.tsx, src/layouts/auth/InputResetPassLayout.tsx, src/layouts/auth/ResetPassLayout.tsx, src/pages/auth/inputresetpass.tsx, src/pages/auth/redirecting.tsx, src/pages/auth/verified.tsx
Reset Password and Verification should be working
=> Firebase Redirection Fixes

src/components/table/restaurantCards/Voting.tsx, src/components/table/tableSelection/TableCard.tsx, src/components/table/tableSelection/createTable/CreateTable.tsx, src/components/table/tableSelection/createTable/IndividualTable.tsx, src/layouts/table/tableSelected/TableSelectedLayout.tsx, src/lib/firebase/table/TableOperations.ts, src/pages/tables/[tableid]/voting.tsx, src/types/Table.ts
- Added a loader to show fetching restaurants
- Restaurants are now cached only once per table creation
=> implemented loaidng restuarants on table creation

src/components/NavBar.tsx
=> Login Works

src/layouts/table/tableSelected/TableSelectedLayout.tsx, src/layouts/table/tableSelection/UserTablesLayout.tsx, src/lib/firebase/FirestoreOperations.ts, src/lib/firebase/table/TableOperations.ts, src/pages/tables/[tableid]/index.tsx, src/pages/tables/index.tsx, src/types/Table.ts
=> misc fixes for scaling problems

src/components/auth/SocialButtons.tsx, src/layouts/auth/CreateUsernameLayout.tsx, src/layouts/auth/DeleteAccountLayout.tsx, src/layouts/auth/LoginLayout.tsx, src/pages/auth/index.tsx, src/pages/auth/login.tsx
- Google Sign In Fixed
- Same username fixed
=> Small Errors Fixed

src/layouts/table/tableSelected/TableSelectedLayout.tsx, src/pages/tables/[tableid]/index.tsx, src/types/Table.ts
-fixed multiple users joining table
-fixed log out from a specific table page
=> Results page fix

src/layouts/table/tableSelected/TableSelectedLayout.tsx, src/pages/tables/[tableid]/voting.tsx
fixed voting when no params are given
=> fixed empty card stack on no params

src/components/auth/SocialButtons.tsx
=> Github login Working

src/components/table/restaurantCards/FavoritePicker.tsx, src/components/table/tableSelected/RestaurantPreviewCard.tsx, src/pages/tables/[tableid]/results.tsx
- added ranking and number of votes on result page
=> Added ranking and num votes on results

src/components/table/tableSelection/createTable/CreateTable.tsx, src/components/table/tableSelection/createTable/IndividualTable.tsx, src/lib/firebase/table/TableOperations.ts, src/pages/tables/[tableid]/results.tsx, src/types/Table.ts
- Revamped results page
- Showed crowd favorites
- Added leader picked random recommendation
=> Results ranking

src/layouts/table/tableSelected/TableSelectedLayout.tsx
=> added reset to sorting in preview
